### ISSUE TITLE
Questions about hardcoding

### ISSUE THREAD

**Issue by fdx-xdf** [oldboy21/RflDllOb#1]
pDllHeader->header == 0x44434241
Sorry to ask a question about where this fixed value comes from, it looks as if it is ABCD

**Comment by oldboy21** [comment]
it is an header so it can be whatever you want. It is set to ABCD just as an example it's just a tag that helps finding the first bytes of the DLL in memory

**Comment by fdx-xdf** [comment]
Can I adjust it？

**Comment by fdx-xdf** [comment]
Isn't the beginning of the DLL the mz header

**Comment by oldboy21** [comment]
yes, here i explain step by step how i use it and why i use it https://oldboy21.github.io/posts/2023/12/all-i-want-for-christmas-is-reflective-dll-injection/

**Comment by fdx-xdf** [comment]
I apologize for my stupid question. I just read the code for inject, and there I understood all my questions
